// Compose ScannerCam Light store screenshots: raw device captures -> framed,
// captioned, on-brand marketing images at exact store dimensions.
//
// Render engine: headless Google Chrome (no npm deps). Each image's HTML is
// generated by frame.mjs, written to a temp file, and screenshotted at exactly
// {w}x{h} via --window-size + --force-device-scale-factor=1.
//
//   node store/template/build.mjs            # build all (from store/raw/)
//   node store/template/build.mjs --preview  # build previews (from --map below)
//
import { readFileSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildHtml } from './frame.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..', '..'); // repo root
const STORE = join(ROOT, 'store');

const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';

// Canvas sizes per device class (store-listing dimensions).
export const CANVAS = {
  'ios-iphone': { w: 1320, h: 2868 },
  'ios-ipad': { w: 2048, h: 2732 },
  'android-phone': { w: 1080, h: 2400 },
  'android-tablet': { w: 1600, h: 2560 },
};

// The 6 core screens, in listing order, with caption copy.
export const SCREENS = [
  { key: 'scan', caption: 'Crisp scans in one tap', sub: 'Automatic edge detection nails the page every time' },
  { key: 'library', caption: 'Your documents, organized', sub: 'Search, sort, rename — everything in one place' },
  { key: 'filters', caption: 'Auto-enhance every page', sub: 'Auto, Color and Grayscale filters that just work' },
  { key: 'pdf', caption: 'Export polished PDFs', sub: 'Share clean, professional documents instantly' },
  { key: 'search', caption: 'Find any word, instantly', sub: 'Full-text search reads inside every scan' },
  { key: 'privacy', caption: '100% private', sub: 'No ads, no tracking — nothing leaves your device' },
];

function dataUri(file) {
  const b64 = readFileSync(file).toString('base64');
  return `data:image/png;base64,${b64}`;
}

function renderOne({ outPath, caption, sub, rawPath, deviceStyle, w, h }) {
  const html = buildHtml({
    caption,
    subcaption: sub,
    screenshotDataUri: dataUri(rawPath),
    deviceStyle,
    w,
    h,
  });
  const tmpHtml = join(STORE, '_preview', `_tmp_${deviceStyle}_${Math.abs(hash(outPath))}.html`);
  mkdirSync(dirname(tmpHtml), { recursive: true });
  writeFileSync(tmpHtml, html);
  mkdirSync(dirname(outPath), { recursive: true });
  execFileSync(CHROME, [
    '--headless',
    '--disable-gpu',
    '--hide-scrollbars',
    '--force-device-scale-factor=1',
    `--window-size=${w},${h}`,
    `--screenshot=${outPath}`,
    `file://${tmpHtml}`,
  ], { stdio: 'ignore' });
}

function hash(s) { let h = 0; for (const c of s) h = (h * 31 + c.charCodeAt(0)) | 0; return h; }

const args = process.argv.slice(2);
const preview = args.includes('--preview');

if (preview) {
  // Preview against existing marketing raws to lock the aesthetic.
  const P = join(ROOT, 'apps/web/assets/screenshots');
  const map = [
    { deviceStyle: 'android-phone', raw: join(P, 'hero.png'), screen: SCREENS[0], out: 'preview-phone-scan.png' },
    { deviceStyle: 'android-phone', raw: join(P, 'library.png'), screen: SCREENS[1], out: 'preview-phone-library.png' },
    { deviceStyle: 'android-phone', raw: join(P, 'pdf-export.png'), screen: SCREENS[3], out: 'preview-phone-pdf.png' },
    { deviceStyle: 'android-phone', raw: join(P, 'search.png'), screen: SCREENS[4], out: 'preview-phone-search.png' },
    { deviceStyle: 'ios-ipad', raw: join(P, 'appstore-ipad/hero.png'), screen: SCREENS[0], out: 'preview-ipad-scan.png' },
  ];
  for (const m of map) {
    if (!existsSync(m.raw)) { console.warn('skip (no raw):', m.raw); continue; }
    const c = CANVAS[m.deviceStyle];
    const outPath = join(STORE, '_preview', m.out);
    renderOne({ outPath, caption: m.screen.caption, sub: m.screen.sub, rawPath: m.raw, deviceStyle: m.deviceStyle, ...c });
    console.log('built', outPath);
  }
} else {
  // Production: consume store/raw/<class>/<screen>.png -> store/final/<class>/<screen>.png
  let built = 0, missing = [];
  for (const deviceStyle of Object.keys(CANVAS)) {
    const c = CANVAS[deviceStyle];
    for (const s of SCREENS) {
      const rawPath = join(STORE, 'raw', deviceStyle, `${s.key}.png`);
      if (!existsSync(rawPath)) { missing.push(`${deviceStyle}/${s.key}`); continue; }
      const outPath = join(STORE, 'final', deviceStyle, `${String(SCREENS.indexOf(s) + 1).padStart(2, '0')}-${s.key}.png`);
      renderOne({ outPath, caption: s.caption, sub: s.sub, rawPath, deviceStyle, ...c });
      console.log('built', outPath);
      built++;
    }
  }
  console.log(`\n${built} images built.`);
  if (missing.length) console.warn(`MISSING raw captures (${missing.length}):\n  ` + missing.join('\n  '));
}
